### ISSUE TITLE
I need to edit more.

### ISSUE THREAD

**Issue by FriedTM** [datasone/grub-mod-setup_var#17]
setup_var_3 0x924 0xC80 does not work it just sets it to 0x80 which will almost brick any pc. had to get a ic programmer

**Comment by datasone** [comment]
A new release has been made with variable sized values, you may be interested in the `setup_var_vs` command, it can set value with multi bytes. A problem is (as said in the README) I can't test if that command functions as expected, that is, I can't decide if the values is stored in little endian or big endian. Now I assumes it's in little endian, but if it's actually stored in big endian, things would mess up.
BTW, if the value have broken your PC, you may look into the `setup_var_cv` section as well, as the variable you need to change is possibly stored in another varstore, and you may have changed something completely irrelevant.

**Comment by FriedTM** [comment]
Hey im not worried about bricking it. I have an ic flasher, i have bricked it so many times and reflashed. I am also certain that is the correct address because i can set it to really slow ram there. Finally, OMG thanks so much! Ill test this out on Monday for sure 👍

**Comment by arachnophilia1997** [comment]
Hello. I have a similar question. Hope it's ok if i hijack this thread for my own purposes. I'm trying to adjust a option. But any attempts, such as ` setup_var 0x6ba 0x4e2`, cause 0x6ba to return 0xba after reboot. I've tried setup_var2 and 3 too, but it seems as if I have to use the new command. Not sure how though, since i haven't used the VarStores at all to adjust anything else. I hope you can help.

[...]
Form: Memory Overclocking Menu, Form ID: 0x27AB {01 86 AB 27 70 13}
[...]
0x3CEE2 	Setting: Memory Voltage, Variable: 0x6BA {05 94 77 13 78 13 1F 04 01 00 BA 06 10 11 00 00 72 06 00 00}

0x3CEF6 		Option: Default, Value: 0x0		{09 08 4A 13 31 01 00 00}
0x3CEFE 		Option: 1.10 Volts, Value: 0x44C	{09 08 79 13 01 01 4C 04}
0x3CF06 		Option: 1.15 Volts, Value: 0x47E	{09 08 7A 13 01 01 7E 04}
0x3CF0E 		Option: 1.20 Volts, Value: 0x4B0	{09 08 7B 13 01 01 B0 04}
0x3CF16 		Option: 1.25 Volts, Value: 0x4E2	{09 08 7C 13 01 01 E2 04}
0x3CF1E 		Option: 1.30 Volts, Value: 0x514	{09 08 7D 13 01 01 14 05}
0x3CF26 		Option: 1.35 Volts, Value: 0x546	{09 08 7E 13 01 01 46 05}
0x3CF2E 		Option: 1.40 Volts, Value: 0x578	{09 08 7F 13 01 01 78 05}
0x3CF36 		Option: 1.45 Volts, Value: 0x5AA	{09 08 80 13 01 01 AA 05}
0x3CF3E 		Option: 1.50 Volts, Value: 0x5DC	{09 08 81 13 01 01 DC 05}
0x3CF46 		Option: 1.55 Volts, Value: 0x60E	{09 08 82 13 01 01 0E 06}
0x3CF4E 		Option: 1.60 Volts, Value: 0x640	{09 08 83 13 01 01 40 06}
0x3CF56 		Option: 1.65 Volts, Value: 0x672	{09 08 84 13 01 01 72 06}
0x3CF5E 	End of Options {29 02}

 snipped from my ifr extraction .txt found here: https://github.com/arachnophilia1997/help/blob/main/extrakt.txt?raw=true

**Comment by datasone** [comment]
> Hello. I have a similar question. Hope it's ok if i hijack this thread for my own purposes. I'm trying to adjust a option. But any attempts, such as ` setup_var 0x6ba 0x4e2`, cause 0x6ba to return 0xba after reboot. I've tried setup_var2 and 3 too, but it seems as if I have to use the new command. Not sure how though, since i haven't used the VarStores at all to adjust anything else. I hope you can help.
> 
> [...]
> Form: Memory Overclocking Menu, Form ID: 0x27AB {01 86 AB 27 70 13}
> [...]
> 0x3CEE2 Setting: Memory Voltage, Variable: 0x6BA {05 94 77 13 78 13 1F 04 01 00 BA 06 10 11 00 00 72 06 00 00}
> 
> 0x3CEF6 Option: Default, Value: 0x0 {09 08 4A 13 31 01 00 00}
> 0x3CEFE Option: 1.10 Volts, Value: 0x44C {09 08 79 13 01 01 4C 04}
> 0x3CF06 Option: 1.15 Volts, Value: 0x47E {09 08 7A 13 01 01 7E 04}
> 0x3CF0E Option: 1.20 Volts, Value: 0x4B0 {09 08 7B 13 01 01 B0 04}
> 0x3CF16 Option: 1.25 Volts, Value: 0x4E2 {09 08 7C 13 01 01 E2 04}
> 0x3CF1E Option: 1.30 Volts, Value: 0x514 {09 08 7D 13 01 01 14 05}
> 0x3CF26 Option: 1.35 Volts, Value: 0x546 {09 08 7E 13 01 01 46 05}
> 0x3CF2E Option: 1.40 Volts, Value: 0x578 {09 08 7F 13 01 01 78 05}
> 0x3CF36 Option: 1.45 Volts, Value: 0x5AA {09 08 80 13 01 01 AA 05}
> 0x3CF3E Option: 1.50 Volts, Value: 0x5DC {09 08 81 13 01 01 DC 05}
> 0x3CF46 Option: 1.55 Volts, Value: 0x60E {09 08 82 13 01 01 0E 06}
> 0x3CF4E Option: 1.60 Volts, Value: 0x640 {09 08 83 13 01 01 40 06}
> 0x3CF56 Option: 1.65 Volts, Value: 0x672 {09 08 84 13 01 01 72 06}
> 0x3CF5E End of Options {29 02}
> 
> snipped from my ifr extraction .txt found here: https://github.com/arachnophilia1997/help/blob/main/extrakt.txt?raw=true

The VarStore info can be obtained with newer IFR-Extractor [here](https://github.com/LongSoft/Universal-IFR-Extractor/releases). Here it seems right (only two varstores have size larger than 0x6ba, "Setup" and "DellPassword", the latter may hardly be right ), though you can check again with the tool I mentioned.
If you want to set this value, using `setup_var_vs 0x6BA 0x02 0x4E2` should be enough, the `0x02` is the variable size (2 bytes here).

P.S. Playing with voltage settings is rather dangerous and may result in hardware damage, so I don't recommend using this tool to achieve this. The problem is that this tool only modify the stored settings value, but it's the BIOS code that reads this value and sets the corresponding voltage. The OEM may not test hidden settings well and there may be bugs in the BIOS code, which may lead to unexpected results.

**Comment by FriedTM** [comment]
How do you know how many bits they are and how do i use the cv command?

**Comment by datasone** [comment]
If you use the new IFR-Extractor, the variable would look like this:
```
One Of: Ipv6 PXE Support, VarStoreInfo (VarOffset/VarName): 0x2, VarStore: 0x24, QuestionId: 0x3DE, Size: 1
```
And the size to be used in the cv command is the size here.
