### ISSUE TITLE
Can you tag new release?

### ISSUE THREAD

**Issue by johnnynunez** [datasone/grub-mod-setup_var#3]

**Comment by datasone** [comment]
I didn't make a new release as there is nothing new about the code and the only change after the release now is 3f15bf2f206f181c5a501f82cad7b3e0f370faa1, which only fixes the guide link due to the deprecation of the [AptioFixPkg](https://github.com/acidanthera/AptioFixPkg).

So now I'm not sure whether to make this commit into a new release. Do you think it is necessary? If so, I will make it.

**Comment by johnnynunez** [comment]
@datasone I would like you to make a new release. There are people like me who do not have linux or macOS to build without problems. Please and thank you!

**Comment by datasone** [comment]
OK, [new release](https://github.com/datasone/grub-mod-setup_var/releases/tag/1.1) has been made.
